name: Install apexpy in conda environments

on:
  workflow_dispatch:

jobs:
  install-apexpy:
    name: Using (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - name: Mamba info
        shell: bash -el {0}
        run: mamba info
      - name: Update environment
        shell: bash -el {0}
        run: mamba install fortran-compiler meson
      - name: Install apexpy
        shell: bash -el {0}
        run: pip install git+https://github.com/aburrell/apexpy.git@rc_v2.0.1
      - name: Test apexpy
        shell: bash -el {0}
        run: python -c "import apexpy"
  
