name: Install apexpy in conda environments

on:
  workflow_dispatch:

jobs:
  install-apexpy:
    name: Using (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - name: Add build dependencies (Linux)
        if: runner.os == 'Linux'
        run: mamba install fortran-compiler
      - name: Add build dependencies (macOS)
        if: runner.os == 'macOS'
        run: mamba install fortran-compiler
      - name: Add build dependencies (Windows)
        if: runner.os == 'Windows'
        # Just trying everything that might help...
        # https://github.com/conda-forge/compilers-feedstock
        # https://github.com/conda-forge/vc-feedstock
        run: |
          mamba install fortran-compiler cxx-compiler c-compiler vc vs2015_runtime vs2017_win-64 vs2019_win-64 vs2022_win-64
      - name: Mamba info & list
        run: |
          mamba info
          mamba list
      - name: Install apexpy
        run: pip install git+https://github.com/aburrell/apexpy.git@rc_v2.0.1
      - name: Test apexpy
        run: python -c "import apexpy"
