on:
  workflow_dispatch:

jobs:
  deploy-panel-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: mkdir html
      - run: pip install jupyter nbconvert panel pandas markdown tabulate
      - run: git clone https://github.com/smithara/swarm-handbook-experiment.git
      - run: jupyter nbconvert --to script swarm-handbook-experiment/json/json_creator.ipynb
      - run: panel convert swarm-handbook-experiment/json/json_creator.py --to pyodide-worker --out html/pyodide --index --requirements pandas markdown tabulate
      - run: cp -r swarm-handbook-experiment/json/catalog html/pyodide/catalog
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
