name: Install apexpy on Windows

on:
  workflow_dispatch:

jobs:
  install-apexpy:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022]
        python-version: ["3.10"]

    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install apexpy (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        python -m pip install git+https://github.com/aburrell/apexpy.git@v2.0.1

    - name: Test apexpy
      run: python -c "import apexpy"
