name: Install apexpy on Windows

on:
  workflow_dispatch:

jobs:
  install-apexpy:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
        python-version: ["3.10"]

    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

#     - name: Setup gfortran (Windows)
#       uses: msys2/setup-msys2@v2
#       if: runner.os == 'Windows'
#       with:
#         install: >-
#           base-devel

#     - name: Install apexpy (Windows)
#       if: runner.os == 'Windows'
#       shell: msys2 {0}
#       run: |
#         python -m pip install numpy
#         python -m pip install git+https://github.com/aburrell/apexpy.git@rc_v2.0.1

    - name: Setup gfortran (Windows)
      if: runner.os == 'Windows'
      run: |
           choco install rtools --no-progress
           echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH

    - name: Install apexpy (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install git+https://github.com/aburrell/apexpy.git@rc_v2.0.1

    - name: Test apexpy
      run: python -c "import apexpy"
