name: Install apexpy on Windows

on:
  workflow_dispatch:

jobs:
  install-apexpy:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-latest]
        python-version: ["3.8"]
    
    steps:

    - name: Setup gfortran (Windows)
      uses: msys2/setup-msys2@v2
      if: runner.os == 'Windows'
      with:
        install: >-
          base-devel

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install apexpy (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pip install numpy
        python -m pip install --no-use-pep517 apexpy

    - name: Test apexpy
      run: python -c "import apexpy"
