name: Install apexpy

on:
  workflow_dispatch:

jobs:
  install-apexpy:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ windows-2022, ubuntu-24.04 ]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install apexpy (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $GITHUB_PATH
        python -m pip install git+https://github.com/aburrell/apexpy.git@v2.1.0
    
    - name: Install apexpy (Linux)
      if: runner.os == 'Linux'
      run: python -m pip install git+https://github.com/aburrell/apexpy.git@v2.1.0

    - name: Test apexpy
      run: python -c "import apexpy"
