on:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: --hook-stage manual --all-files

  pre-commit-pipx:
    runs-on: ubuntu-latest
    steps:
     - run: pipx run pre-commit run --all
